export const CHANGE_CURRENT_SEARCH = 'CHANGE_CURRENT_SEARCH';

export const SET_LAST_LOCATION_NAME = 'SET_LAST_LOCATION_NAME';
export const SET_LAST_LOCATION_IMG_URLS = 'SET_LAST_LOCATION_IMG_URLS';
export const SET_LAST_LOCATION_YT_VID_URL = 'SET_LAST_LOCATION_YT_VID_URL';
export const SET_LAST_LOCATION_NEWS_ARTICLES = 'SET_LAST_LOCATION_NEWS_ARTICLES';
export const SET_LAST_LOCATION_REVIEWS = 'SET_LAST_LOCATION_REVIEWS';

export const BUCKET_ADD_LOCATION = 'BUCKET_ADD_LOCATION';
export const BUCKET_REMOVE_LOCATION = 'BUCKET_REMOVE_LOCATION';
